name: Build roundcubemail Docker images

on:
  # Allow manual runs.
  workflow_dispatch:
  # Also run on updates to this repo.
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
  pull_request:
    paths-ignore:
      - '**/*.md'

env:
  PLATFORMS: linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/amd64

jobs:

  build-image:
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        VARIANT: ['apache', 'fpm', 'fpm-alpine']

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "true"

      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v1.0.1

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v1.0.3

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Get current roundcube version number
        run: echo "ROUNDCUBE_VERSION=${1:-$(curl -fsS https://roundcube.net/VERSION.txt)}" >> $GITHUB_ENV

      - name: Build roundcubemail Docker image
        if: ${{ github.ref != 'refs/heads/main' }}
        uses: docker/build-push-action@v2.1.0
        with:
          context: roundcubemail-docker/${{ matrix.VARIANT }}
          file: roundcubemail-docker/${{ matrix.VARIANT }}/Dockerfile
          tags: |
            florianpiesche/roundcubemail:latest
            florianpiesche/roundcubemail:${{ env.ROUNDCUBE_VERSION }}
            ghcr.io/${{ github.repository_owner }}/roundcubemail:latest
            ghcr.io/${{ github.repository_owner }}/roundcubemail:${{ env.ROUNDCUBE_VERSION }}
          platforms: ${{ env.PLATFORMS }}
          push: false

      - name: Build and push roundcubemail Docker image
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/build-push-action@v2.1.0
        with:
          context: roundcubemail-docker/${{ matrix.VARIANT }}
          file: roundcubemail-docker/${{ matrix.VARIANT }}/Dockerfile
          tags: |
            florianpiesche/roundcubemail:latest
            florianpiesche/roundcubemail:${{ env.ROUNDCUBE_VERSION }}
            ghcr.io/${{ github.repository_owner }}/roundcubemail:latest
            ghcr.io/${{ github.repository_owner }}/roundcubemail:${{ env.ROUNDCUBE_VERSION }}
          platforms: ${{ env.PLATFORMS }}
          push: true
