name: Build roundcubemail Docker images

on:
  # Allow manual runs.
  workflow_dispatch:
  # Also run on updates to this repo.
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
  pull_request:
    paths-ignore:
      - '**/*.md'

env:
  PLATFORMS: linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/amd64
  PUSH_IMAGE: ${{ github.ref == 'refs/heads/main' }}

jobs:

  build-image:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        VARIANT: ['apache', 'fpm', 'fpm-alpine']

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "true"

      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v1

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        if: ${{ env.PUSH_IMAGE == 'true' }}
        uses: docker/login-action@v2 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        if: ${{ env.PUSH_IMAGE == 'true' }}
        uses: docker/login-action@v2 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Get current roundcube version number
        run: echo "ROUNDCUBE_VERSION=${1:-$(curl -fsS https://roundcube.net/VERSION.txt)}" >> $GITHUB_ENV

      - name: Build and push roundcubemail Docker image
        uses: docker/build-push-action@v3
        with:
          context: roundcubemail-docker/${{ matrix.VARIANT }}
          file: roundcubemail-docker/${{ matrix.VARIANT }}/Dockerfile
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME || 'nobody' }}/roundcubemail:latest
            ${{ secrets.DOCKERHUB_USERNAME || 'nobody' }}/roundcubemail:${{ env.ROUNDCUBE_VERSION }}
            ghcr.io/${{ github.repository_owner }}/roundcubemail:latest
            ghcr.io/${{ github.repository_owner }}/roundcubemail:${{ env.ROUNDCUBE_VERSION }}
          platforms: ${{ env.PLATFORMS }}
          push: ${{ env.PUSH_IMAGE }}
